
package restaurant.capa1_presentacion;

/**
 *
 * @author Lain
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        asignarLookandfeel();
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }
    
    private void asignarLookandfeel(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGestionarLector = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuGestionarAutor = new javax.swing.JMenuItem();
        menuGestionarEditorial = new javax.swing.JMenuItem();
        menuGestionarEspecialidad = new javax.swing.JMenuItem();
        menuGestionarLibro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRegistrarPedido = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("“SOFTWARE DE RESTAURANT CON DISEÑO ARQUITECTURAL N-CAPAS”");
        setName("formMenu"); // NOI18N

        jMenu1.setText("Administración");

        menuGestionarLector.setText("Gestionar Producto");
        menuGestionarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarLectorActionPerformed(evt);
            }
        });
        jMenu1.add(menuGestionarLector);
        jMenu1.add(jSeparator1);

        menuGestionarAutor.setText("Gestionar Mesa");
        jMenu1.add(menuGestionarAutor);

        menuGestionarEditorial.setText("Gestionar Mozo");
        jMenu1.add(menuGestionarEditorial);

        menuGestionarEspecialidad.setText("Gestionar Cliente ");
        menuGestionarEspecialidad.setToolTipText("");
        jMenu1.add(menuGestionarEspecialidad);

        menuGestionarLibro.setText("Gestionar Libro");
        jMenu1.add(menuGestionarLibro);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Procesos");

        menuRegistrarPedido.setText("Registrar Pedido ");
        menuRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarPedidoActionPerformed(evt);
            }
        });
        jMenu2.add(menuRegistrarPedido);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        jMenuItem7.setText("Genrar Reporte Pedidos");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Seguridad");

        jMenuItem8.setText("Gestionar Usuario");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Gestionar Permisos");
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Aplicación");

        jMenuItem10.setText("Ayuda");
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Acerca de");
        jMenu5.add(jMenuItem11);
        jMenu5.add(jSeparator2);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu5.add(menuSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarPedidoActionPerformed
        FormRegistrarPedido formRegistrarProducto = new FormRegistrarPedido(this,true);
        formRegistrarProducto.setVisible(true);
    }//GEN-LAST:event_menuRegistrarPedidoActionPerformed

    private void menuGestionarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarLectorActionPerformed
        
    }//GEN-LAST:event_menuGestionarLectorActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuGestionarAutor;
    private javax.swing.JMenuItem menuGestionarEditorial;
    private javax.swing.JMenuItem menuGestionarEspecialidad;
    private javax.swing.JMenuItem menuGestionarLector;
    private javax.swing.JMenuItem menuGestionarLibro;
    private javax.swing.JMenuItem menuRegistrarPedido;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
